import { getYtDlpExec } from '../core/binaries.js';
import { sleep } from '../core/retry.js';

/**
 * Motor generico baseado no yt-dlp (via youtube-dl-exec, binario standalone,
 * sem necessidade de Python).
 *
 * Usado pelos adaptadores finos de YouTube e redes sociais (Facebook,
 * Instagram, TikTok, X/Twitter, Reddit, Twitch, Vimeo, etc.). O yt-dlp mantem
 * as logicas de decifracao/anti-bot atualizadas pela comunidade; aqui apenas
 * consumimos o dump JSON (URLs ja decifradas) e reaproveitamos o fluxo
 * existente de download/mux do projeto.
 */

/** Tentativas máximas da análise quando o spawn do yt-dlp está bloqueado. */
export const YTDLP_ANALYZE_MAX_ATTEMPTS = 3;

export const YTDLP_FORMAT_UNAVAILABLE = 'YTDLP_FORMAT_UNAVAILABLE';

/** Prefixo das URIs de variantes adaptativas escolhidas no CLI/Electron. */
export const ADAPTIVE_URI_PREFIX = 'ytdlp-format:';

/**
 * Padroes de erro do yt-dlp que indicam conteudo autenticado/restrito.
 * Usados para oferecer a dica de cookies quando a analise falha.
 */
const LOGIN_REQUIRED_HINTS = [
  'sign in',
  'signin',
  'log in',
  'login',
  'private',
  'requires authentication',
  'authentication required',
  'you must be logged in',
  'members only',
  'this video is only available',
  'requested format is not available',
  '403 forbidden',
  'forbidden',
];

/** Detecta se o stderr do yt-dlp indica conteúdo autenticado/restrito. */
export function isLoginRequiredError(stderr) {
  const text = String(stderr || '').toLowerCase();
  return LOGIN_REQUIRED_HINTS.some((hint) => text.includes(hint));
}

/**
 * Opcoes padrao do yt-dlp para obter apenas o JSON de formatos.
 * - preferFreeFormats: prefere formatos com codecs abertos (vp9/opus) quando
 *   disponiveis, mantendo tambem os demais formatos no JSON.
 * Nota: --no-call-home e --youtube-skip-dash-manifest foram deprecados no
 * yt-dlp 2026+ (call-home removido; skip de manifesto DASH virou automatico),
 * entao nao sao mais enviados.
 */
function buildBaseOptions() {
  return {
    dumpSingleJson: true,
    noWarnings: true,
    noCheckCertificates: true,
    preferFreeFormats: true,
  };
}

function sortFormats(a, b) {
  return b.height - a.height || b.bitrate - a.bitrate || b.itag - a.itag;
}

function sortVariants(a, b) {
  const scoreA = `${a.sourceKind || ''}` === 'adaptive' ? 1 : 0;
  const scoreB = `${b.sourceKind || ''}` === 'adaptive' ? 1 : 0;
  return scoreB - scoreA || (b.height || 0) - (a.height || 0) || (b.bandwidth || 0) - (a.bandwidth || 0) || (b.itag || 0) - (a.itag || 0);
}

/**
 * Calcula o bitrate em bps. Prefere a estimativa por filesize/duration (mais
 * precisa). O yt-dlp vem reportando tbr/vbr/abr em kbps nos formatos atuais
 * (confirmado por filesize x duracao), entao o fallback converte para bps.
 */
function computeBitrate(format) {
  const duration = Number(format.duration) || 0;
  const size = Number(format.filesize || format.filesize_approx) || 0;
  if (duration > 0 && size > 0) return Math.round((size * 8) / duration);
  const raw = Number(format.tbr || format.vbr || format.abr) || 0;
  if (!raw) return 0;
  return raw < 1_000_000 ? Math.round(raw * 1000) : Math.round(raw);
}

/**
 * Converte um formato do JSON do yt-dlp no mesmo shape usado antigamente pelo
 * parseYouTubePlayerResponse (src/youtube.js), para nao quebrar o CLI/Electron.
 * P12: extrai language e audio_track do JSON do yt-dlp.
 */
function mapYtDlpFormat(format) {
  const codecs = [format.vcodec, format.acodec].filter(Boolean).join(', ');
  // P12: extract language from audio_track or top-level field
  const language = format.language
    || format.audio_track?.language
    || '';
  const label = format.audio_track?.title
    || format.format_note
    || '';
  const isDefault = Boolean(format.audio_track?.default);
  return {
    itag: Number(format.format_id) || 0,
    formatId: String(format.format_id || ''),
    url: format.url || '',
    mimeType: format.ext ? `video/${format.ext}` : '',
    container: format.ext || '',
    codecs,
    qualityLabel: format.format_note || (format.height ? `${format.height}p` : ''),
    bitrate: computeBitrate(format),
    width: Number(format.width) || 0,
    height: Number(format.height) || 0,
    fps: Number(format.fps) || 0,
    audioQuality: format.acodec && format.acodec !== 'none' ? 'AUDIO_QUALITY_MEDIUM' : '',
    hasVideo: Boolean(format.vcodec && format.vcodec !== 'none'),
    hasAudio: Boolean(format.acodec && format.acodec !== 'none'),
    contentLength: Number(format.filesize || format.filesize_approx) || 0,
    signatureCipher: '',
    // P12: audio/subtitle metadata
    language,
    label,
    isDefault,
    isAutoGenerated: false,
  };
}

/**
 * Analisa qualquer URL suportada pelo yt-dlp e devolve a mesma estrutura de
 * analise esperada pelo CLI/Electron:
 *   { kind, pageUrl, title, videoId, durationSeconds, progressiveFormats,
 *     adaptiveFormats, adaptiveVideoFormats, adaptiveAudioFormats, variants }
 * Os variants de video adaptativo usam a URI "ytdlp-format:<formatId>" e os
 * progressivos usam a URL direta (mesmo contrato de src/youtube.js).
 */
export async function analyzeYtDlpUrl(url, headers = {}, auth = {}) {
  // Sprint 4.2: circuit breaker — reject immediately if platform is rate-limiting
  if (ytdlpAnalysisBreaker.isOpen()) {
    const err = new Error('yt-dlp analysis temporarily blocked (circuit breaker open). Try again later.');
    err.code = 'YTDLP_CIRCUIT_OPEN';
    throw err;
  }

  const userAgent = headers?.['user-agent'] || headers?.['User-Agent'];
  const cookiesFile = auth?.cookiesFile || '';
  const cookiesFromBrowser = auth?.cookiesFromBrowser || '';
  const baseOptions = {
    ...buildBaseOptions(),
    ...(userAgent ? { userAgent } : {}),
    ...(cookiesFile ? { cookies: cookiesFile } : {}),
    ...(cookiesFromBrowser ? { cookiesFromBrowser } : {}),
  };

  // P10: o spawn do yt-dlp pode ser bloqueado temporariamente pelo Windows
  // (Defender) na 1a execucao do binario recem-instalado — erro transitorio
  // (EPERM/EBUSY/access denied) que desaparece em alguns segundos. Erros reais
  // do yt-dlp (login, 403, formato) nao passam por retry.
  let info = null;
  let lastErr = null;
  for (let attempt = 1; attempt <= YTDLP_ANALYZE_MAX_ATTEMPTS; attempt++) {
    try {
      const exec = await getYtDlpExec();
      info = await exec(url, baseOptions);
      ytdlpAnalysisBreaker.recordSuccess();
      break;
    } catch (err) {
      lastErr = err;
      const stderr = String(err.stderr || err.message || '');
      if (!isSpawnBlockedError(stderr) || attempt === YTDLP_ANALYZE_MAX_ATTEMPTS) break;
      await sleep(2000 * attempt);
    }
  }

  if (!info) {
    const stderr = String(lastErr.stderr || lastErr.message || '');
    const needsAuth = isLoginRequiredError(stderr);
    const spawnBlocked = isSpawnBlockedError(stderr);

    // Sprint 4.2: record platform errors (403/429) in circuit breaker
    if (needsAuth && !spawnBlocked) {
      ytdlpAnalysisBreaker.recordFailure();
    }

    const cause = new Error(
      needsAuth
        ? `Conteudo autenticado/restrito: o yt-dlp nao conseguiu acessar sem login. Exporte os cookies do navegador (extensao "Get cookies.txt LOCALLY") e use --cookies <arquivo>, ou use --cookies-from-browser chrome/edge/firefox. Detalhes: ${lastErr.message || String(lastErr)}`
        : spawnBlocked
          ? `O Windows ainda esta verificando o yt-dlp (primeira execucao apos a instalacao). Aguarde alguns segundos e tente novamente. Detalhes: ${lastErr.message || String(lastErr)}`
          : `Nao foi possivel analisar o video com o yt-dlp: ${lastErr.message || String(lastErr)}`
    );
    cause.code = 'YTDLP_ANALYZE_FAILED';
    cause.stderr = lastErr.stderr || '';
    cause.needsAuth = needsAuth;
    throw cause;
  }

  return buildAnalysisFromInfo(info, url);
}

/** Padroes de stderr que indicam spawn bloqueado (Windows Defender na 1a execucao). */
const SPAWN_BLOCKED_HINTS = [
  'eperm',
  'ebusy',
  'eacces',
  'eagain',
  'emfile',
  'enoent',
  'access is denied',
  '0xc0000135', // STATUS_DLL_NOT_FOUND
  '0xc0000022', // STATUS_ACCESS_DENIED
];

/** true se o stderr indica spawn bloqueado/transitorio (nao erro do yt-dlp). */
export function isSpawnBlockedError(stderr) {
  const s = String(stderr || '').toLowerCase();
  return SPAWN_BLOCKED_HINTS.some((hint) => s.includes(hint));
}

/** Monta a analise a partir do dump JSON bruto do yt-dlp. */
/**
 * Agrupa formatos de áudio por idioma, ordenados por bitrate desc.
 * Cada idioma gera um AudioTrack com 1+ formatos.
 * P12.1: audio track grouping.
 */
function buildAudioTracks(audioFormats) {
  const byLang = new Map();
  for (const f of audioFormats) {
    const lang = f.language || 'und';
    if (!byLang.has(lang)) {
      byLang.set(lang, {
        language: lang,
        label: f.label || lang,
        isDefault: f.isDefault,
        formats: [],
      });
    }
    byLang.get(lang).formats.push(f);
  }
  // Sort: default first, then by format count (more formats = richer track)
  return [...byLang.values()].sort((a, b) => {
    if (a.isDefault !== b.isDefault) return a.isDefault ? -1 : 1;
    return b.formats.length - a.formats.length;
  });
}

/**
 * Extrai legendas do JSON do yt-dlp (chaves subtitles + automatic_captions).
 * Legendas manuais têm prioridade sobre automáticas.
 * P12.1: subtitle track extraction.
 */
function buildSubtitleTracks(info) {
  const tracks = [];
  const seen = new Set();

  // Manual subtitles
  for (const [lang, entries] of Object.entries(info?.subtitles || {})) {
    const best = entries.find((e) => e.ext === 'vtt') || entries[0];
    if (!best) continue;
    const key = `${lang}:manual`;
    if (seen.has(key)) continue;
    seen.add(key);
    tracks.push({
      language: lang,
      label: best.name || lang,
      isAutoGenerated: false,
      isDefault: false,
      format: { ext: best.ext || 'vtt', url: best.url || '' },
    });
  }

  // Auto-generated subtitles (ASR) — only if no manual version exists
  for (const [lang, entries] of Object.entries(info?.automatic_captions || {})) {
    if (seen.has(`${lang}:manual`)) continue;
    const best = entries.find((e) => e.ext === 'vtt') || entries[0];
    if (!best) continue;
    tracks.push({
      language: lang,
      label: `${lang} (auto)`,
      isAutoGenerated: true,
      isDefault: false,
      format: { ext: best.ext || 'vtt', url: best.url || '' },
    });
  }

  return tracks;
}

function buildAnalysisFromInfo(info, url) {
  const rawFormats = Array.isArray(info?.formats) ? info.formats : [];

  const progressiveFormats = rawFormats
    .filter((f) => f.vcodec && f.vcodec !== 'none' && f.acodec && f.acodec !== 'none' && f.url)
    .map(mapYtDlpFormat)
    .sort(sortFormats);

  const adaptiveVideoFormats = rawFormats
    .filter((f) => f.vcodec && f.vcodec !== 'none' && (!f.acodec || f.acodec === 'none') && f.url)
    .map(mapYtDlpFormat)
    .sort(sortFormats);

  const adaptiveAudioFormats = rawFormats
    .filter((f) => (!f.vcodec || f.vcodec === 'none') && f.acodec && f.acodec !== 'none' && f.url)
    .map(mapYtDlpFormat)
    .sort((a, b) => b.bitrate - a.bitrate || b.itag - a.itag);

  const adaptiveFormats = [...progressiveFormats, ...adaptiveVideoFormats, ...adaptiveAudioFormats].sort(sortFormats);

  if (!progressiveFormats.length && !adaptiveVideoFormats.length) {
    const err = new Error(
      'O yt-dlp nao retornou nenhum formato utilizavel para esta URL (pode ser restrita, ao vivo, protegida por DRM ou indisponivel).'
    );
    err.code = YTDLP_FORMAT_UNAVAILABLE;
    throw err;
  }

  const variants = [
    ...progressiveFormats.map((format) => ({
      uri: format.url,
      resolution: format.qualityLabel || (format.height ? `${format.height}p` : ''),
      width: format.width,
      height: format.height,
      bandwidth: format.bitrate,
      codecs: format.codecs,
      itag: format.itag,
      container: format.container,
      sourceKind: 'progressive',
    })),
    ...adaptiveVideoFormats.map((format) => ({
      uri: `${ADAPTIVE_URI_PREFIX}${format.formatId}`,
      resolution: format.qualityLabel || (format.height ? `${format.height}p` : ''),
      width: format.width,
      height: format.height,
      bandwidth: format.bitrate,
      codecs: format.codecs,
      itag: format.itag,
      container: format.container,
      sourceKind: 'adaptive',
    })),
  ].sort(sortVariants);

  return {
    kind: 'ytdlp',
    pageUrl: url,
    title: info.title || 'Video',
    videoId: info.id || '',
    durationSeconds: Number(info.duration) || 0,
    progressiveFormats,
    adaptiveFormats,
    adaptiveVideoFormats,
    adaptiveAudioFormats,
    hlsManifestUrl: info.hls_manifest_url || '',
    dashManifestUrl: info.dash_manifest_url || '',
    variants,
    // P12: audio tracks + subtitles
    audioTracks: buildAudioTracks(adaptiveAudioFormats),
    subtitleTracks: buildSubtitleTracks(info),
  };
}

/**
 * Prepara o download a partir da variante escolhida no CLI/Electron.
 * - "ytdlp-format:<formatId>" -> mux (video + melhor audio) via FFmpeg
 * - URL direta (progressivo)    -> download unico
 *
 * P12.1: accepts `audioLanguage` and `allAudio` options.
 */
export async function prepareYtDlpDownload({ analysis, selectedUrl, headers = {}, auth = {}, audioLanguage, allAudio } = {}) {
  if (selectedUrl?.startsWith(ADAPTIVE_URI_PREFIX)) {
    const formatId = selectedUrl.slice(ADAPTIVE_URI_PREFIX.length);
    const video = analysis?.adaptiveVideoFormats?.find((format) => format.formatId === formatId) || null;
    if (!video || !video.url) {
      const err = new Error(`Formato adaptativo ${formatId} nao encontrado na analise.`);
      err.code = YTDLP_FORMAT_UNAVAILABLE;
      throw err;
    }

    // P12.1: all-audio mode — download all audio tracks as mux-multi
    if (allAudio && analysis?.adaptiveAudioFormats?.length > 1) {
      const audioFormats = analysis.adaptiveAudioFormats.filter((f) => f.url);
      if (audioFormats.length > 1) {
        const videoBytes = video.contentLength || undefined;
        const totalAudioBytes = audioFormats.reduce((sum, f) => sum + (f.contentLength || 0), 0);
        return {
          strategy: 'mux-multi',
          videoUrl: video.url,
          audioUrls: audioFormats.map((f) => f.url),
          audioLabels: audioFormats.map((f) => f.label || f.language || ''),
          audioLanguages: audioFormats.map((f) => f.language || 'und'),
          chosenFormat: { sourceKind: 'adaptive', formatId, height: video.height },
          videoBytes,
          totalBytes: videoBytes ? videoBytes + totalAudioBytes : undefined,
          durationMs: (analysis?.durationSeconds || 0) * 1000,
        };
      }
    }

    // P12.1: select audio by language if specified, otherwise best available
    let bestAudio;
    if (audioLanguage && analysis?.adaptiveAudioFormats) {
      bestAudio = analysis.adaptiveAudioFormats.find((f) => f.language === audioLanguage) || null;
      if (!bestAudio?.url) {
        // Fallback to best available if requested language not found
        bestAudio = analysis?.adaptiveAudioFormats?.[0] || null;
      }
    } else {
      bestAudio = analysis?.adaptiveAudioFormats?.[0] || null;
    }
    if (!bestAudio?.url) {
      // Sem audio disponivel: entrega apenas o video (fallback gracioso).
      return {
        strategy: 'single',
        downloadUrl: video.url,
        chosenFormat: { sourceKind: 'adaptive', formatId, height: video.height },
        totalBytes: video.contentLength || undefined,
        durationMs: (analysis?.durationSeconds || 0) * 1000,
      };
    }

    const videoBytes = video.contentLength || undefined;
    const audioBytes = bestAudio.contentLength || undefined;
    return {
      strategy: 'mux',
      videoUrl: video.url,
      audioUrl: bestAudio.url,
      chosenFormat: { sourceKind: 'adaptive', formatId, height: video.height },
      videoBytes,
      audioBytes,
      totalBytes: videoBytes && audioBytes ? videoBytes + audioBytes : undefined,
      durationMs: (analysis?.durationSeconds || 0) * 1000,
    };
  }

  const progressive = analysis?.progressiveFormats?.find((format) => format.url === selectedUrl) || null;
  if (progressive?.url) {
    return {
      strategy: 'single',
      downloadUrl: progressive.url,
      chosenFormat: { sourceKind: 'progressive', formatId: progressive.formatId, height: progressive.height },
      totalBytes: progressive.contentLength || undefined,
      durationMs: (analysis?.durationSeconds || 0) * 1000,
    };
  }

  if (selectedUrl) {
    return { strategy: 'single', downloadUrl: selectedUrl };
  }

  const err = new Error('Nenhuma variante de download selecionada.');
  err.code = YTDLP_FORMAT_UNAVAILABLE;
  throw err;
}

// ---------------------------------------------------------------------------
// Circuit breaker for repeated platform errors (403/429) — Sprint 4.2
// ---------------------------------------------------------------------------

/**
 * Simple circuit breaker: opens after `threshold` consecutive failures,
 * stays open for `cooldownMs`, then transitions to half-open (allows one try).
 */
export class CircuitBreaker {
  /**
   * @param {object} [opts]
   * @param {number} [opts.threshold] — consecutive failures to open (default 3)
   * @param {number} [opts.cooldownMs] — ms to stay open (default 60 000)
   */
  constructor({ threshold = 3, cooldownMs = 60_000 } = {}) {
    this._failures = 0;
    this._threshold = threshold;
    this._cooldownMs = cooldownMs;
    this._openedAt = 0;
  }

  /** Returns true when the circuit is open (calls should be rejected). */
  isOpen() {
    if (this._failures < this._threshold) return false;
    if (Date.now() - this._openedAt > this._cooldownMs) {
      this._failures = 0; // half-open: allow one try
      return false;
    }
    return true;
  }

  recordFailure() {
    this._failures++;
    this._openedAt = Date.now();
  }

  recordSuccess() {
    this._failures = 0;
  }

  reset() {
    this._failures = 0;
    this._openedAt = 0;
  }
}

/** Global circuit breaker for yt-dlp analysis (platform 403/429). */
const ytdlpAnalysisBreaker = new CircuitBreaker();
